/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demogamebannhap;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.Timer;
/**
 *
 * @author E7440
 */
public class BanNhap extends javax.swing.JFrame {

    /**
     * Creates new form BanNhap
     */
    public BanNhap() {
        initComponents();
        
        //maingame();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        bot6 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        bot5 = new javax.swing.JLabel();
        bot4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        bot3 = new javax.swing.JLabel();
        bot2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        bot1 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        bot = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        bot7 = new javax.swing.JLabel();
        bot8 = new javax.swing.JLabel();
        bot9 = new javax.swing.JLabel();
        bot10 = new javax.swing.JLabel();
        duongdi = new javax.swing.JLabel();
        bot11 = new javax.swing.JLabel();
        bot12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\rock3.PNG")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\rock3.PNG")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 80, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\rock3.PNG")); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 90, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\rock3.PNG")); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 90, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel15.setText("jLabel15");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 80, 80));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 80));

        jLabel76.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 80, 80));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 80));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(60, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 60, 80));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 260, 160));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 260, 160));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 270, 80));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 270, 90));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel21.setText("jLabel21");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel22.setText("jLabel22");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel24.setText("jLabel24");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 60, 80));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        jButton7.setText("jButton7");
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton7KeyReleased(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 40, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel25.setText("jLabel25");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 80));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel26.setText("jLabel26");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 80));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 80));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 60, 80));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 80, 80));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 80, 80));

        jLabel34.setText("jLabel26");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 80));

        jLabel35.setText("jLabel19");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel36.setText("jLabel21");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel37.setText("jLabel22");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel39.setText("jLabel19");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel40.setText("jLabel21");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel42.setText("jLabel21");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel43.setText("jLabel19");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel44.setText("jLabel19");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel45.setText("jLabel21");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel46.setText("jLabel22");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel48.setText("jLabel25");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 80));

        jLabel50.setText("jLabel21");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel51.setText("jLabel25");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 80));

        jLabel52.setText("jLabel19");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel53.setText("jLabel19");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel54.setText("jLabel22");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel55.setText("jLabel21");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel57.setText("jLabel19");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel58.setText("jLabel21");
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel59.setText("jLabel22");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel60.setText("jLabel19");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel61.setText("jLabel21");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel62.setText("jLabel21");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel63.setText("jLabel19");
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel64.setText("jLabel19");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel65.setText("jLabel25");
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 80));

        jLabel67.setText("jLabel22");
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel69.setText("jLabel22");
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel70.setText("jLabel21");
        jPanel3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel71.setText("jLabel19");
        jPanel3.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel72.setText("jLabel21");
        jPanel3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel73.setText("jLabel22");
        jPanel3.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel74.setText("jLabel21");
        jPanel3.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel75.setText("jLabel25");
        jPanel3.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 80));

        jLabel77.setText("jLabel15");
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, 80));

        jLabel78.setText("jLabel22");
        jPanel3.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel79.setText("jLabel13");
        jPanel3.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel80.setText("jLabel21");
        jPanel3.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel82.setText("jLabel21");
        jPanel3.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel83.setText("jLabel21");
        jPanel3.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel84.setText("jLabel17");
        jPanel3.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 80, 80));

        jLabel87.setText("jLabel22");
        jPanel3.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));
        jPanel3.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 80));

        jLabel89.setText("jLabel19");
        jPanel3.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel90.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 60, 80));

        bot6.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot6.setText("jLabel160");
        bot6.setToolTipText("");
        jPanel3.add(bot6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, 50));

        jLabel91.setText("jLabel19");
        jPanel3.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel93.setText("jLabel21");
        jPanel3.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel94.setText("jLabel22");
        jPanel3.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel95.setText("jLabel18");
        jPanel3.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 80));

        jLabel96.setText("jLabel16");
        jPanel3.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 80));

        jLabel97.setText("jLabel19");
        jPanel3.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel98.setText("jLabel26");
        jPanel3.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 80));

        jLabel99.setText("jLabel22");
        jPanel3.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel100.setText("jLabel19");
        jPanel3.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel101.setText("jLabel21");
        jPanel3.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel103.setText("jLabel21");
        jPanel3.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel104.setText("jLabel26");
        jPanel3.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 80));

        jLabel105.setText("jLabel19");
        jPanel3.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel106.setText("jLabel19");
        jPanel3.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel107.setText("jLabel21");
        jPanel3.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel109.setText("jLabel19");
        jPanel3.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel111.setText("jLabel19");
        jPanel3.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 80));

        jLabel113.setText("jLabel22");
        jPanel3.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 60, 80));

        jLabel115.setText("jLabel29");
        jPanel3.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 80));

        jLabel116.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 80, 80));

        jLabel117.setText("jLabel25");
        jPanel3.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 60, 80));

        jLabel118.setText("jLabel21");
        jPanel3.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel121.setText("jLabel13");
        jPanel3.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel123.setText("jLabel15");
        jPanel3.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, 80));

        jLabel125.setText("jLabel21");
        jPanel3.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel126.setText("jLabel15");
        jPanel3.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, 80));

        jLabel128.setText("jLabel13");
        jPanel3.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel131.setText("jLabel13");
        jPanel3.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel135.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel135.setText("jLabel15");
        jLabel135.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, 80));

        jLabel136.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel136.setText("jLabel13");
        jLabel136.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel137.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel137.setText("jLabel13");
        jLabel137.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel141.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel141.setText("jLabel21");
        jLabel141.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 80));

        jLabel145.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel145.setText("jLabel13");
        jLabel145.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 80));

        jLabel146.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel146.setText("jLabel15");
        jLabel146.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, 80));

        jLabel147.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel147.setText("jLabel16");
        jLabel147.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 80));

        jLabel148.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel148.setText("jLabel17");
        jLabel148.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 80, 80));

        jLabel149.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel149.setText("jLabel149");
        jLabel149.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 90, 80));

        jLabel150.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel150.setText("jLabel150");
        jLabel150.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 90, 80));

        jLabel151.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel151.setText("jLabel151");
        jLabel151.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 80, 80));

        jLabel154.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\cauthang.PNG")); // NOI18N
        jLabel154.setText("jLabel154");
        jLabel154.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 160, 90, 80));

        jLabel156.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel156.setText("jLabel156");
        jLabel156.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(799, 160, 80, 80));

        jLabel157.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel157.setText("jLabel157");
        jLabel157.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 80, 70));

        jLabel158.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel158.setText("jLabel158");
        jLabel158.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 90, 70));

        jLabel159.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel159.setText("jLabel159");
        jLabel159.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 90, 70));

        bot5.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot5.setText("jLabel161");
        bot5.setMaximumSize(new java.awt.Dimension(124, 60));
        bot5.setMinimumSize(new java.awt.Dimension(124, 60));
        jPanel3.add(bot5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 50, 50));

        bot4.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot4.setText("jLabel162");
        jPanel3.add(bot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 50, 50));

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel32.setText("jLabel32");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 90, 80));

        bot3.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot3.setText("jLabel163");
        jPanel3.add(bot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 50, 50));

        bot2.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot2.setText("jLabel164");
        jPanel3.add(bot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 50, 50));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel33.setText("jLabel33");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 70, 80));

        bot1.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot1.setText("jLabel165");
        jPanel3.add(bot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 50, 50));

        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 80, 80));

        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 90, 80));

        jLabel138.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel138.setText("jLabel14");
        jLabel138.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, 80));

        bot.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot.setText("jLabel38");
        jPanel3.add(bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 50, 50));
        jPanel3.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 70, 80));

        jLabel132.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel132.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 70, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, 80));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 90, 80));

        bot7.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot7.setText("jLabel8");
        jPanel3.add(bot7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 50, 50));

        bot8.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot8.setText("jLabel38");
        jPanel3.add(bot8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 50, 50));

        bot9.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot9.setText("jLabel49");
        jPanel3.add(bot9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 50, 50));

        bot10.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot10.setText("jLabel56");
        jPanel3.add(bot10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 50, 50));

        duongdi.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        duongdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(duongdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 90, 80));

        bot11.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot11.setText("jLabel66");
        jPanel3.add(bot11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 50, 50));

        bot12.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\Capture.PNG")); // NOI18N
        bot12.setText("jLabel68");
        jPanel3.add(bot12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 70, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 80, 80));

        jLabel152.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel152.setText("jLabel152");
        jLabel152.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 90, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, 80));

        jLabel7.setBackground(new java.awt.Color(255, 255, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\đuongi.PNG")); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 90, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 950, 520));

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 70, 40));

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, 70, 40));

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 70, 40));

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 639, 70, 40));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 70, 40));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\down.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 70, 40));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 60, 40));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\down.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 70, 40));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 70, 40));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 70, 40));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\up.png")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, 70, 40));

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\up.png")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, 70, 40));

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\E7440\\OneDrive\\Pictures\\BlueStacks\\right.png")); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 70, 40));

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton16.setText("RUN");
        jButton16.setFocusable(false);
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton16MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton16MouseReleased(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 710, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        bot8.setVisible(false);
        bot9.setVisible(true);
        jLabel38.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        bot9.setVisible(false);
        bot10.setVisible(true);
        jLabel76.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        bot10.setVisible(false);
        bot11.setVisible(true);
        duongdi.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        bot11.setVisible(false);
        bot12.setVisible(false);
        //JOptionPane.showMessageDialog(null, "ban da thang!!!");
        //bot0.setVisible(true);
        jButton16.setEnabled(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //bot0.setVisible(false);
        jLabel24.setVisible(false);
        bot6.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jLabel27.setVisible(false);
        bot5.setVisible(true);
        bot6.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bot5.setVisible(false);
        bot6.setVisible(false);
        bot4.setVisible(true);
        jLabel31.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bot5.setVisible(false);
        bot6.setVisible(false);
        bot4.setVisible(false);
        jLabel30.setVisible(false);
        bot3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        bot3.setVisible(false);
        bot2.setVisible(true);
        jLabel32.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        bot2.setVisible(false);
        bot1.setVisible(true);
        jLabel33.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        bot1.setVisible(false);
        bot.setVisible(true);
        jLabel138.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        bot.setVisible(false);
        bot7.setVisible(true);
        jLabel132.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        bot7.setVisible(false);
        bot8.setVisible(true);
        jLabel8.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton16MousePressed

    private void jButton16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton16MouseReleased

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Thread thr = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //bot0.setVisible(false);
                    jLabel24.setVisible(false);
                    bot6.setVisible(true);
                    Thread.sleep(1000);
                    jLabel27.setVisible(false);
                    bot5.setVisible(true);
                    bot6.setVisible(false);
                    Thread.sleep(1000);
                    bot5.setVisible(false);
                    bot6.setVisible(false);
                    bot4.setVisible(true);
                    jLabel31.setVisible(false);
                    Thread.sleep(1000);
                    bot5.setVisible(false);
                    bot6.setVisible(false);
                    bot4.setVisible(false);
                    jLabel30.setVisible(false);
                    bot3.setVisible(true);
                    Thread.sleep(1000);
                    bot3.setVisible(false);
                    bot2.setVisible(true);
                    jLabel32.setVisible(false);
                    Thread.sleep(1000);
                    bot2.setVisible(false);
                    bot1.setVisible(true);
                    jLabel33.setVisible(false);
                    Thread.sleep(1000);
                    bot1.setVisible(false);
                    bot.setVisible(true);
                    jLabel138.setVisible(false);
                    Thread.sleep(1000);
                    bot.setVisible(false);
                    bot7.setVisible(true);
                    jLabel132.setVisible(false);
                    Thread.sleep(1000);
                    bot7.setVisible(false);
                    bot8.setVisible(true);
                    jLabel8.setVisible(false);
                    Thread.sleep(1000);
                    bot8.setVisible(false);
                    bot9.setVisible(true);
                    jLabel38.setVisible(false);
                    Thread.sleep(1000);
                    bot9.setVisible(false);
                    bot10.setVisible(true);
                    jLabel76.setVisible(false);
                    Thread.sleep(1000);
                    bot10.setVisible(false);
                    bot11.setVisible(true);
                    duongdi.setVisible(false);
                    Thread.sleep(1000);
                    bot11.setVisible(false);
                    bot12.setVisible(false);
                    //JOptionPane.showMessageDialog(null, "ban da thang!!!");
                    //bot0.setVisible(true);
                    jButton16.setEnabled(true);
                } catch (Exception e) {
                }
            }
        });
        thr.start();

        jButton16.setEnabled(false);

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyReleased
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jButton7KeyReleased

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
      

        
    }//GEN-LAST:event_jButton7KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bot;
    private javax.swing.JLabel bot1;
    private javax.swing.JLabel bot10;
    private javax.swing.JLabel bot11;
    private javax.swing.JLabel bot12;
    private javax.swing.JLabel bot2;
    private javax.swing.JLabel bot3;
    private javax.swing.JLabel bot4;
    private javax.swing.JLabel bot5;
    private javax.swing.JLabel bot6;
    private javax.swing.JLabel bot7;
    private javax.swing.JLabel bot8;
    private javax.swing.JLabel bot9;
    private javax.swing.JLabel duongdi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */

 

    

   
}
