/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

/**
 *
 * @author E7440
 */
public class ThietKeMayTinh extends javax.swing.JFrame {
    String sohang1 = "";
    String sohang2 = "";
    
    boolean bl = false;
    /**
     * Creates new form ThietKeMayTinh
     */
    public ThietKeMayTinh() {
        initComponents();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        number1 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        btchia = new javax.swing.JButton();
        btcanbac2 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        btnhan = new javax.swing.JButton();
        btphantram = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        bttru = new javax.swing.JButton();
        bt1chia = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        btcongchiatru = new javax.swing.JButton();
        btc = new javax.swing.JButton();
        btcong = new javax.swing.JButton();
        bang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTFActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(4, 5));

        number1.setText("1");
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });
        jPanel1.add(number1);

        number2.setText("2");
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });
        jPanel1.add(number2);

        number3.setText("3");
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });
        jPanel1.add(number3);

        btchia.setText("/");
        btchia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchiaActionPerformed(evt);
            }
        });
        jPanel1.add(btchia);

        btcanbac2.setText("sqrt");
        btcanbac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcanbac2ActionPerformed(evt);
            }
        });
        jPanel1.add(btcanbac2);

        number4.setText("4");
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });
        jPanel1.add(number4);

        number5.setText("5");
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });
        jPanel1.add(number5);

        number6.setText("6");
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });
        jPanel1.add(number6);

        btnhan.setText("*");
        btnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnhan);

        btphantram.setText("%");
        btphantram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btphantramActionPerformed(evt);
            }
        });
        jPanel1.add(btphantram);

        number7.setText("7");
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });
        jPanel1.add(number7);

        number8.setText("8");
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });
        jPanel1.add(number8);

        number9.setText("9");
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });
        jPanel1.add(number9);

        bttru.setText("-");
        bttru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttruActionPerformed(evt);
            }
        });
        jPanel1.add(bttru);

        bt1chia.setText("1/x");
        bt1chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1chiaActionPerformed(evt);
            }
        });
        jPanel1.add(bt1chia);

        number0.setText("0");
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });
        jPanel1.add(number0);

        btcongchiatru.setText("+/-");
        btcongchiatru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcongchiatruActionPerformed(evt);
            }
        });
        jPanel1.add(btcongchiatru);

        btc.setText("C");
        btc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcActionPerformed(evt);
            }
        });
        jPanel1.add(btc);

        btcong.setText("+");
        btcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcongActionPerformed(evt);
            }
        });
        jPanel1.add(btcong);

        bang.setText("=");
        bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangActionPerformed(evt);
            }
        });
        jPanel1.add(bang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTF)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTFActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        // TODO add your handling code here:
         if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
        
        
    }//GEN-LAST:event_number1ActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        // TODO add your handling code here:
         if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
       
    }//GEN-LAST:event_number2ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        // TODO add your handling code here:
          if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
        
    }//GEN-LAST:event_number3ActionPerformed

    private void btchiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchiaActionPerformed
        // TODO add your handling code here:
         String cmd = evt.getActionCommand();
        
        sohang2 = cmd;
        sohang1 = txtTF.getText();
        
        txtTF.setText("");
    }//GEN-LAST:event_btchiaActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        // TODO add your handling code here:
          if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
         
    }//GEN-LAST:event_number4ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        // TODO add your handling code here:
         if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
        
    }//GEN-LAST:event_number5ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        // TODO add your handling code here:
          if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
         
    }//GEN-LAST:event_number6ActionPerformed

    private void btnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhanActionPerformed
        // TODO add your handling code here:
         String cmd = evt.getActionCommand();
        
        sohang2 = cmd;
        sohang1 = txtTF.getText();
        
        txtTF.setText("");
    }//GEN-LAST:event_btnhanActionPerformed

    private void btphantramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btphantramActionPerformed
        // TODO add your handling code here:
        if(bl){
            bl = false;
            txtTF.setText("");
        } 
        
        if(txtTF.getText().equals("")){
             return;
         }
         
         String cmd = evt.getActionCommand();
         try{
             double value = Double.parseDouble(txtTF.getText());
             
             if(cmd.equals("%")){
                 value = value * 100;
             }
             txtTF.setText("" + value);
             
             bl = true;
         }
         catch(Exception ex){
             ex.printStackTrace();
         }
    }//GEN-LAST:event_btphantramActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        // TODO add your handling code here:
          if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
        
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        // TODO add your handling code here:
          if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
        
    }//GEN-LAST:event_number8ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        // TODO add your handling code here:
          if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
         
    }//GEN-LAST:event_number9ActionPerformed

    private void bttruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttruActionPerformed
        // TODO add your handling code here:
          String cmd = evt.getActionCommand();
        
        sohang2 = cmd;
        sohang1 = txtTF.getText();
        
        txtTF.setText("");
    }//GEN-LAST:event_bttruActionPerformed

    private void bt1chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1chiaActionPerformed
        // TODO add your handling code here:
       
        
        
        if(txtTF.getText().equals("")){
             return;
         }
         
         String cmd = evt.getActionCommand();
         try{
             double value = Double.parseDouble(txtTF.getText());
             
             if(cmd.equals("1/x")){
                 value = 1/value;
             }
             txtTF.setText("" + value);
             bl =true;
         }
         catch(Exception ex){
             ex.printStackTrace();
         }
    }//GEN-LAST:event_bt1chiaActionPerformed

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        // TODO add your handling code here:
         if(bl){
            bl = false;
            txtTF.setText("");
        } 
        String cmd = evt.getActionCommand();
        txtTF.setText(txtTF.getText() + cmd );
         
    }//GEN-LAST:event_number0ActionPerformed

    private void btcongchiatruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcongchiatruActionPerformed
        // TODO add your handling code here:
       
        
        try{
             double value = Double.parseDouble(txtTF.getText());
             value = - value;
             
             txtTF.setText(""+  value);
         }
         catch(Exception ex){
             ex.printStackTrace();
         }
    }//GEN-LAST:event_btcongchiatruActionPerformed

    private void btcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcActionPerformed
        // TODO add your handling code here:
        txtTF.setText("");
        sohang1 ="";
        sohang2="";
        bl =false;
    }//GEN-LAST:event_btcActionPerformed

    private void btcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcongActionPerformed
        // TODO add your handling code here:
         String cmd = evt.getActionCommand();
        
        sohang2 = cmd;
        sohang1 = txtTF.getText();
        
        txtTF.setText("");
    }//GEN-LAST:event_btcongActionPerformed

    private void bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangActionPerformed
        // TODO add your handling code here:
     
        
        if(txtTF.getText().equals("") || sohang1.equals("")){
            return;
        }
        
        try{
            double sh1 = Double.parseDouble(sohang1);
            double sh2 = Double.parseDouble(txtTF.getText());
            double result =0;
            
            if(sohang2.equals("+")){
                result = sh1 + sh2;
            }else if(sohang2.equals("-")){
                result = sh1 - sh2;
            }else if(sohang2.equals("*")){
                result = sh1 * sh2;
            }else if(sohang2.equals("/")){
                result = sh1 / sh2;
            }
            txtTF.setText(""+ result);
            bl = true;
        }
        catch(Exception  ex){
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_bangActionPerformed

    private void btcanbac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcanbac2ActionPerformed
        // TODO add your handling code here:
        
        if(txtTF.getText().equals("")){
             return;
         }
         
         String cmd = evt.getActionCommand();
         try{
             double value = Double.parseDouble(txtTF.getText());
             
             if(cmd.equals("sqrt")){
                 value = Math.sqrt(value);
             }
             txtTF.setText("" + value);
             bl = true;
         }
         catch(Exception ex){
             ex.printStackTrace();
         }
    }//GEN-LAST:event_btcanbac2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThietKeMayTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThietKeMayTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThietKeMayTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThietKeMayTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThietKeMayTinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bang;
    private javax.swing.JButton bt1chia;
    private javax.swing.JButton btc;
    private javax.swing.JButton btcanbac2;
    private javax.swing.JButton btchia;
    private javax.swing.JButton btcong;
    private javax.swing.JButton btcongchiatru;
    private javax.swing.JButton btnhan;
    private javax.swing.JButton btphantram;
    private javax.swing.JButton bttru;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JTextField txtTF;
    // End of variables declaration//GEN-END:variables
}
